In [2]:
import pandas as pd

In [4]:
import pandas as pd

df = pd.read_csv('audience.csv')

df.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [5]:
print(df.columns.tolist())

['date', 'user_id', 'view_adverts']

In [6]:
df['date'] = pd.to_datetime(df['date'])

november_df = df[
    (df['date'] >= '2023-11-01') &
    (df['date'] < '2023-12-01')
]

mau = november_df['user_id'].nunique()

print('MAU за ноябрь:', mau)

MAU за ноябрь: 7639

In [7]:
df['date'] = pd.to_datetime(df['date'])

dau = df.groupby('date')['user_id'].nunique()

print(dau)

date
2023-11-01    623
2023-11-02    649
2023-11-03    573
2023-11-04    343
2023-11-05    350
2023-11-06    660
2023-11-07    629
2023-11-08    600
2023-11-09    661
2023-11-10    583
2023-11-11    354
2023-11-12    377
2023-11-13    646
2023-11-14    687
2023-11-15    690
2023-11-16    639
2023-11-17    585
2023-11-18    412
2023-11-19    378
2023-11-20    711
2023-11-21    651
2023-11-22    608
2023-11-23    632
2023-11-24    595
2023-11-25    366
2023-11-26    372
2023-11-27    589
2023-11-28    610
2023-11-29    621
2023-11-30    620
Name: user_id, dtype: int64

In [8]:
df['date'] = pd.to_datetime(df['date']).dt.normalize()

users_nov1 = set(
    df.loc[df['date'] == '2023-11-01', 'user_id']
)

users_nov2 = set(
    df.loc[df['date'] == '2023-11-02', 'user_id']
)

returned_users = users_nov1 & users_nov2

retention_d1 = len(returned_users) / len(users_nov1) * 100

print(f'Retention D1: {retention_d1:.1f}%')

Retention D1: 26.6%

Голубой продукт: Демонстрирует классическую здоровую кривую удержания. Вначале наблюдается закономерный отток пользователей, но со временем график выходит на плато (примерно на уровне 40% к Day 4 – Day 7). Это означает, что у продукта есть ядро лояльной аудитории, которая регулярно продолжает им пользоваться.

Розовый продукт: Имеет катастрофическое падение показателей. Кривая стремительно падает вниз и полностью обнуляется к 5-му дню (Day 5), достигая 0%. Это свидетельствует о том, что продукт не представляет долгосрочной ценности для пользователей, в нем отсутствует вовлеченность или критически сломан пользовательский опыт (UX/onboarding).

Сравнение продуктов:
На старте (Day 0 и Day 1) показатели обоих продуктов примерно сопоставимы и находятся на высоком уровне.
Начиная со 2-го дня (Day 2), голубой продукт начинает значительно выигрывать по удержанию: на 2-й день у него удерживается около 53% пользователей, в то время как у розового — только около 40%.

In [10]:
df['date'] = pd.to_datetime(df['date'])

november = df[
    (df['date'] >= '2023-11-01') &
    (df['date'] < '2023-12-01')
]

# Все уникальные пользователи за ноябрь
all_users = november['user_id'].nunique()

# Пользователи, посмотревшие хотя бы одно объявление
ad_users = november.loc[
    november['view_adverts'] > 0, 'user_id'
].nunique()

# Конверсия в процентах
conversion = ad_users / all_users * 100

print('Всего пользователей:', all_users)
print('Посмотрели объявления:', ad_users)
print(f'Конверсия: {conversion:.1f}%')

Всего пользователей: 7639
Посмотрели объявления: 3538
Конверсия: 46.3%

In [12]:
df['date'] = pd.to_datetime(df['date'])

november = df[
    (df['date'] >= '2023-11-01') &
    (df['date'] < '2023-12-01')
]

average_views = (
    november['view_adverts'].sum()
    / november['user_id'].nunique()
)

print(round(average_views, 2))

2.87

In [13]:
total_users = 2000
critics = 500
promoters = 1200
neutrals = 300

promoters_percent = promoters / total_users * 100
critics_percent = critics / total_users * 100

nps = promoters_percent - critics_percent

print('NPS:', nps, '%')

NPS: 35.0 %

In [23]:
import pandas as pd

df_ab = pd.read_csv('audience2.csv')
df_ab.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [24]:
print(df_ab.columns)

Index(['experiment_num', 'experiment_group', 'user_id', 'revenue'], dtype='object')

In [25]:
for exp in sorted(df_ab['experiment_num'].unique()):
    data = df_ab[df_ab['experiment_num'] == exp]

    test = data[data['experiment_group'] == 'test']['revenue']
    control = data[data['experiment_group'] == 'control']['revenue']

    print('Эксперимент:', exp)
    print('ARPU test:', test.mean())
    print('ARPU control:', control.mean())
    print('-------------------')

Эксперимент: 1
ARPU test: 665.7395833333334
ARPU control: 722.4602150537635
-------------------
Эксперимент: 2
ARPU test: 332.9291666666667
ARPU control: 704.6537634408602
-------------------
Эксперимент: 3
ARPU test: 998.66875
ARPU control: 663.2064516129033
-------------------

In [26]:
import pandas as pd

df_listers = pd.read_csv('audience3.csv')

df_listers.head()

   user_id        date  cnt_adverts  age  cnt_contacts  revenue
0      100  2022-01-01            6   21           119       53
1      100  2022-01-02            2   21           200       18
2      100  2022-01-03            6   21           193       42
3      100  2022-01-04            2   21           143       38
4      100  2022-01-05            2   21           190       40

In [27]:
print(df_listers.columns)

Index(['user_id', 'date', 'cnt_adverts', 'age', 'cnt_contacts', 'revenue'], dtype='object')

In [28]:
df_listers['revenue'].mean()

np.float64(30.70253164556962)

In [29]:
print(df_listers.columns)

Index(['user_id', 'date', 'cnt_adverts', 'age', 'cnt_contacts', 'revenue'], dtype='object')

In [30]:
df_listers['age'].median()

28.0

11.Ящик с усами (box plot).

12.ответ №3

13.Поскольку график №3 имеет самый большой разброс значений по оси X (от $-25$ до $5$), эта случайная величина обладает наибольшей дисперсией

14. Scatter Plot
Это классический график для визуализации взаимосвязи двух непрерывных переменных $X$ и $Y$. По расположению точек прямо рассчитывается коэффициент корреляции (здесь видна сильная positive-корреляция).
    Line Plot
На данном графике изображены два временных ряда (две линии зеленых оттенков) во времени. По парным значениям этих двух линий в каждый момент времени можно рассчитать линейную или автокорреляцию.
    Correlation Heatmap
На этом графике коэффициенты корреляции между переменными $X$, $Y$ и $Z$ уже вычислены и прямо отображены числами и цветом.

15.Есть 5% вероятность случайно получить такой или еще более экстремальный результат, если нулевая гипотеза верна.

16.t-тест 
Он подходит для проверки гипотезы о равенстве средних двух выборок из нормального распределения.

17.Квартили делят упорядоченные данные на четыре части, примерно по 25% наблюдений в каждой.

18.Выбрать вариант B (тестовую группу), поскольку его конверсия выше примерно на 9,6% относительно варианта A, а разница статистически значима при уровне значимости 5% (\(p \approx 0{,}035 < 0{,}05\)).